/**
 * 系统版本监视器
 * @author yanrong.tian
 * @date 2021/3/06 14:22:00
 */

 var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};var $alert=document.createElement("div"),isAlerting=!1,$closeIconPre,$closeButtonPre,closeFn=function(){$alert.innerHTML="";isAlerting=!1},VersionMonitor=function(){this.version="<% versionString %>";this.loadSourceError=!1;this.versionFileUrl="./version.json";this.timeoutValue="<% timeoutValue %>";this.init()};
 VersionMonitor.prototype={init:function(){this.addErrorEventListener();this.timeoutVersionListener()},addErrorEventListener:function(){var a=this;window.addEventListener("error",function(b){b&&(b.target||b.srcElement)instanceof HTMLElement&&(a.loadSourceError=!0,a.fetchNewVersion(a.alertReload,"error"))},!0)},fetchNewVersion:function(a,b){var d=this;var c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");c.onreadystatechange=function(){if(4==c.readyState&&200==c.status){var e=
 JSON.parse(c.responseText).versions;e!==d.version&&(d.version=e,a(b))}};c.open("GET",this.versionFileUrl+"?_t="+ +new Date,!0);c.send()},timeoutVersionListener:function(){var a=this;setTimeout(function(){a.fetchNewVersion(a.alertReload,"timeout");a.timeoutVersionListener()},this.timeoutValue)},alertReload:function(a){if(!isAlerting){isAlerting=!0;$alert.innerHTML='<div class="ant-modal-root"><div class="ant-modal-mask"></div><div tabindex="-1" class="ant-modal-wrap " role="dialog" aria-labelledby="rcDialogTitle1"><div role="document" class="ant-modal" style="width: 420px; top: calc((100vh - 200px)/2);"><div tabindex="0" aria-hidden="true" style="width: 0px; height: 0px; overflow: hidden; outline: none;"></div><div class="ant-modal-content"><span class="_tx_close_icon"></span><div class="ant-modal-header"><div class="ant-modal-title" id="rcDialogTitle1">\u7cfb\u7edf\u7248\u672c\u66f4\u65b0</div></div><div class="ant-modal-body">\u53d1\u73b0\u7cfb\u7edf\u6709\u65b0\u7248\u672c\u53d1\u5e03\uff0c\u8bf7\u5237\u65b0\u6d4f\u89c8\u5668\uff0c\u66f4\u65b0\u7cfb\u7edf!</div><div class="ant-modal-footer" style="border:none;"><span class="_tx_close_button" style="margin-right: 10px"></span><span class="_tx_ok_button"></span></div></div></div></div></div>';
 if("timeout"===a){var b=$alert.querySelector("._tx_close_button");a=$alert.querySelector("._tx_ok_button");b.innerHTML='<button type="button" class="ant-btn"><span>\u77e5\u9053\u4e86\uff0c\u6211\u4f1a\u7a0d\u540e\u624b\u52a8\u5237\u65b0</span></button>'}else a=$alert.querySelector("._tx_ok_button");a.innerHTML='<button type="button" class="ant-btn ant-btn-primary"><span>\u5237 \u65b0</span></button>';a&&a.addEventListener("click",function(){window.location.reload()});b&&($closeButtonPre&&$closeButtonPre.removeEventListener("click",
 closeFn),b.addEventListener("click",closeFn),$closeButtonPre=b);document.body.appendChild($alert)}}};new VersionMonitor;
